const chatForm = document.getElementById('chat-form');
const userInput = document.getElementById('user-input');
const chatMessages = document.getElementById('chat-messages');

const BACKEND_URL = 'https://rag-c3793ebc.fastapicloud.dev/ask';

chatForm.addEventListener('submit', async (e) => {
    e.preventDefault();
    const query = userInput.value.trim();
    if (!query) return;

    // 1. Append user message correctly
    appendMessage(query, 'user');
    userInput.value = '';

    // 2. Show loading indicator and save its unique ID
    const loadingId = appendMessage('Analyzing medical literature...', 'assistant loading');

    try {
        const response = await fetch(BACKEND_URL, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ query: query })
        });

        // 3. Successfully remove the loading message using its ID
        const loadingElement = document.getElementById(loadingId);
        if (loadingElement) loadingElement.remove();

        if (response.ok) {
            const data = await response.json();
            appendMessage(data.answer, 'assistant');
        } else {
            const errorData = await response.json();
            appendMessage(`⚠️ <strong>Server Error:</strong> ${errorData.detail || 'Unknown error'}`, 'assistant');
        }
    } catch (error) {
        const loadingElement = document.getElementById(loadingId);
        if (loadingElement) loadingElement.remove();

        appendMessage('⚠️ <strong>Connection Error:</strong> Could not reach the FastAPI backend server.', 'assistant');
    }
});

function appendMessage(text, senderClass) {
    const messageDiv = document.createElement('div');
    // Fixed the parenthesis syntax error here:
    const messageId = 'msg-' + Date.now() + '-' + Math.random().toString(36).substring(2, 7);
    messageDiv.id = messageId;
    messageDiv.className = `message ${senderClass}`;

    // Use innerHTML so HTML tags generated by backend render properly
    if (senderClass.includes('loading')) {
        messageDiv.innerText = text; // Keep plain text for loading status
    } else {
        messageDiv.innerHTML = text; // Render structured HTML for answers
    }

    chatMessages.appendChild(messageDiv);
    chatMessages.scrollTop = chatMessages.scrollHeight;

    return messageId;
}
